INSERT INTO service_providers (name, services, contact_info, description, city) 
VALUES 
('Baker Delight', 'Bakery', '+11234567915 | baker@delight.com', 'Experience the finest baked delicacies in Chicago.', 'Chicago'),
('Chicago Car Care', 'Car Mechanic', '+11234567896 | care@chicagocar.com', 'Premium car maintenance services ensuring smooth drives every time.', 'Chicago'),
('CleanSpace NY', 'Cleaning', '+11234567899 | clean@space.com', 'Revitalize your home with professional cleaning services.', 'New York'),
('Hair Trendz LA', 'Hair Styling', '+11234567910 | trendz@hairla.com', 'Latest hairstyles created by industry-leading stylists in Los Angeles.', 'Los Angeles'),
('Chef’s Delight', 'Cooking', '+11234567904 | chef@delight.com', 'Enjoy gourmet dishes prepared by renowned chefs in Chicago.', 'Chicago'),
('NYC Auto Experts', 'Car Mechanic', '+11234567897 | expert@nycar.com', 'Fast and reliable car repair solutions.', 'New York'),
('Lock & Key Services', 'Locksmith', '+11234567911 | lock@key.com', '24/7 locksmith services ensuring security in New York.', 'New York'),
('LA Gourmet', 'Food', '+11234567908 | gourmet@lafood.com', 'Experience authentic dishes with fresh, local ingredients.', 'Los Angeles'),
('Plumb Perfect', 'Plumbing', '+11234567914 | perfect@plumb.com', 'High-quality plumbing services in New York.', 'New York'),
('Spotless Chicago', 'Cleaning', '+11234567901 | spotless@chicago.com', 'We promise a spotless space, every time.', 'Chicago'),
('Mindful Sessions', 'Counseling', '+11234567905 | mindful@session.com', 'Find balance and peace with our expert counseling services in New York.', 'New York'),
('LA Stitch & Style', 'Clothing Stitching', '+11234567903 | stitch@style.com', 'Bespoke tailoring and clothing stitching services in Los Angeles.', 'Los Angeles'),
('TechFix NY', 'Electronics Repair', '+11234567906 | tech@fixny.com', 'Fast and reliable electronics repair services in New York.', 'New York'),
('Quick Deliveries', 'Package Delivery', '+11234567912 | quick@delivery.com', 'Swift and safe package delivery services in Chicago.', 'Chicago'),
('DriveSafe Mechanics', 'Car Mechanic', '+11234567898 | safe@drive.com', 'Your car’s best friend! Get it serviced today.', 'Chicago'),
('PestBusters', 'Pest Control', '+11234567913 | pest@buster.com', 'Effective and eco-friendly pest control solutions in Los Angeles.', 'Los Angeles'),
('Beauty Box', 'Beauty', '+11234567894 | box@beauty.com', 'Indulge in the best beauty sessions tailored just for you.', 'Los Angeles'),
('LA Shine Cleaners', 'Cleaning', '+11234567900 | shine@laclean.com', 'Eco-friendly cleaning ensuring a fresh and clean environment.', 'Los Angeles'),
('Dust & Shine', 'Cleaning', '+11234567902 | dust@shine.com', 'Experience a cleaner space with our expert services.', 'Los Angeles'),
('EasyMove NYC', 'Relocation', '+11234567916 | easy@move.com', 'Smooth relocation services that prioritize your comfort.', 'New York'),
('LA Movers', 'Relocation', '+11234567917 | la@movers.com', 'From packing to moving, experience a hassle-free relocation.', 'Los Angeles'),
('Foodie’s Paradise', 'Food', '+11234567907 | foodie@paradise.com', 'A culinary journey of diverse flavors and cuisines in Chicago.', 'Chicago'),
('LA AutoFix', 'Car Mechanic', '+11234567895 | auto@fixla.com', 'Your trusted car repair partner in Los Angeles.', 'Los Angeles'),
('LA Beauty Lounge', 'Beauty', '+11234567891 | lounge@beautyla.com', 'A beauty paradise offering state-of-the-art treatments in Los Angeles.', 'Los Angeles'),
('NYC Delicacies', 'Food', '+11234567909 | delicacies@nyc.com', 'Indulge in a variety of mouth-watering delights.', 'New York'),
('Chicago Beauty Bliss', 'Beauty', '+11234567892 | bliss@beautychi.com', 'The leading destination for makeup, skincare, and aesthetics in Chicago.', 'Chicago'),
('LA Plumbing Pros', 'Plumbing', '+11234567915 | pros@plumbla.com', 'Experienced plumbers, ensuring no leaks and perfect flow.', 'Los Angeles'),
('Chicago Relocators', 'Relocation', '+11234567918 | relocator@chi.com', 'Expert relocation services ensuring all your items are safe and secure.', 'Chicago'),
('New York Aesthetic Circle', 'Beauty', '+11234567893 | circle@aesthet.com', 'Transform yourself with our world-class beauty treatments.', 'New York');
