INSERT INTO reviews (provider_id, nickname, content, rating) VALUES
(1, 'BakingLover', 'The pastries are to die for!', 5),
(2, 'CarFan123', 'Got my car repaired here. Top-notch service!', 4),
(2, 'Jess', 'Pretty quick service. The price was reasonable.', 4),
(3, 'CleanFreak', 'My apartment looks brand new after their cleaning service.', 5),
(3, 'Dusty', 'Missed a spot under the bed, but overall good job.', 4),
(4, 'LAHair', 'Loved my new hairstyle!', 5),
(5, 'FoodieMike', 'Chef’s Delight? More like my delight! Great dishes.', 4),
(5, 'HungryHank', 'Delicious, would order again.', 4),
(6, 'SpeedyRecover', 'Got my car fixed in a jiffy!', 5),
(7, 'LockedOutLaura', 'Came to my rescue when I locked myself out. Lifesaver!', 5),
(8, 'TastyTom', 'Ordered from here last week, still thinking about the flavors!', 5),
(8, 'YumYumYum', 'Their dishes never disappoint!', 5),
(9, 'WetWilly', 'Fixed my leaking sink in no time.', 4),
(10, 'TidyUp', 'Exceptional cleaning service. Would highly recommend.', 5),
(11, 'PeacefulMind', 'My therapy sessions here have been transformative.', 5),
(12, 'StitchInTime', 'Got my dress stitched perfectly! Fits like a glove.', 4),
(13, 'TechGeek', 'Fixed my laptop, and it’s faster than ever!', 5),
(14, 'QuickSilver', 'The package got to me right on time!', 4),
(15, 'AutoAnna', 'Trustworthy and reliable mechanics. My car feels brand new.', 5),
(16, 'NoMoreBugs', 'No more cockroaches in my apartment, thanks to them.', 5),
(17, 'BeautyGuru', 'The facials here are just amazing!', 4),
(18, 'ShinySharon', 'The best cleaning service in LA.', 5),
(19, 'NeatNancy', 'They left my home spotless!', 5),
(20, 'EasyPeasy', 'Relocation was smooth. Everything was packed and moved professionally.', 5),
(21, 'MovingManiac', 'Took care of all my items. Nothing was damaged.', 5),
(22, 'DelishDerek', 'Can’t stop thinking about the lasagna I ordered!', 4),
(23, 'GearheadGary', 'Quick diagnosis and repair. Top quality.', 5),
(24, 'BeautyBee', 'A day at this lounge is all you need to rejuvenate.', 4),
(25, 'TasteTester', 'Every dish I ordered was a hit!', 5),
(26, 'MakeupMaggie', 'Got the best facial treatment here.', 5),
(27, 'DripDrop', 'No more clogged drains, thanks to these guys.', 5),
(28, 'MoverMike', 'From packing to unpacking, everything was streamlined.', 5),
(29, 'BeautyBliss', 'Had an amazing spa day here. Felt very pampered.', 5),
(1, 'SweetToothSam', 'Their chocolate cake is pure bliss!', 5),
(3, 'NeatNed', 'Professional cleaners. My place is shining!', 5),
(4, 'HairHelen', 'Didn’t like the haircut much, but the staff was nice.', 3),
(7, 'KeylessKen', 'Swift service at a reasonable price.', 4),
(11, 'MindfulMolly', 'The counselor was very understanding and helpful.', 5),
(16, 'BugBuster', 'Had a pest problem, not anymore. Great service!', 5),
(19, 'CrystalClear', 'Top-notch cleaning service. My home feels fresh!', 5),
(21, 'SmoothMover', 'Relocated without any hitches. Kudos to the team!', 5),
(24, 'PamperPrincess', 'The best beauty treatments in town!', 5),
(27, 'FlowingWater', 'Resolved my plumbing issue quickly.', 5),
(1, 'BakeNBite', 'The bread was freshly baked and tasted heavenly!', 5),
(2, 'GlowingGrace', 'A beauty treatment like no other. My skin feels so refreshed.', 5),
(3, 'MopMaster', 'Booked a deep cleaning service and I’m more than satisfied.', 5),
(4, 'SnipSnapSue', 'A trendy haircut that got me so many compliments!', 5),
(5, 'YumYumYogi', 'The pasta is delicious, and the dessert was the cherry on top!', 4),
(6, 'MechanicMike', 'Trustworthy mechanics. Fixed my car’s engine issue.', 5),
(7, 'UnlockUlysses', 'Locked out at midnight, and they came to the rescue. Grateful!', 5),
(8, 'FeastFred', 'Ordered a three-course meal, and each dish was delectable.', 5),
(9, 'FixItFinn', 'Had a plumbing emergency, and they fixed it promptly.', 5),
(10, 'ScrubnShine', 'The most thorough cleaning service I’ve ever booked.', 5),
(11, 'HeartHealer', 'I feel so much lighter after my counseling session.', 5),
(12, 'StitchSally', 'The tailor did a wonderful job altering my outfit.', 4),
(13, 'TechyTim', 'Repaired my broken phone screen in just an hour.', 5),
(14, 'SpeedySam', 'The package arrived in perfect condition and on time.', 4),
(15, 'AutoAmy', 'Got my car’s brakes fixed. Smooth drive now.', 5),
(16, 'BugOffBen', 'Had a major ant problem, but not anymore. Efficient service.', 5),
(17, 'RadiantRia', 'The facial treatment made my skin glow!', 5),
(18, 'SpotlessSteve', 'Very impressed with their cleaning service. Every corner shines!', 5),
(19, 'PristinePaul', 'Booked a regular cleaning, but the results were extraordinary.', 5),
(20, 'RelocateRuth', 'Moving was stress-free thanks to their professional service.', 5),
(21, 'MunchyMark', 'Their gourmet dishes are a treat for the taste buds.', 5),
(22, 'GearGuy', 'Very knowledgeable mechanics. They explained the issue in detail.', 4),
(23, 'BeautyBlair', 'A relaxing day at the spa. Every treatment felt luxurious.', 5),
(24, 'TastyTina', 'Ordered for a party, and every dish was a hit!', 5),
(25, 'GlowGetter', 'The best beauty treatments at affordable prices.', 5),
(26, 'WaterWalter', 'Had a leaky faucet. They fixed it in no time.', 4),
(27, 'MoveItMax', 'Packing, moving, unpacking - they managed everything perfectly.', 5),
(28, 'YummyYara', 'The bakery items here are simply the best in town.', 5),
(29, 'BeauteousBella', 'From facials to massages, everything is top-notch.', 5),
(2, 'FacialFan', 'My skin feels rejuvenated after the beauty treatment.', 5),
(3, 'ShinyShelby', 'Professional cleaning with attention to detail.', 5),
(6, 'MotorMax', 'Honest pricing and quality work on my car’s repair.', 4),
(7, 'KeyKara', 'Quick response when I was locked out. Highly recommend.', 5),
(9, 'DripDrew', 'Plumbing issue resolved quickly and efficiently.', 4),
(10, 'CleanQueen', 'A clean home is a happy home. Thanks for the amazing service!', 5),
(1, 'BakeNBite', 'The bread was freshly baked but was a bit too hard.', 3),
(2, 'GlowingGrace', 'I didn’t really notice much difference after the facial.', 2),
(2, 'BeautyBeth', 'The spa was calming, but the treatment felt rushed.', 3),
(3, 'CarCarl', 'They fixed one problem, but another one came up.', 2),
(4, 'DustDan', 'Cleaning was okay, but they missed under the furniture.', 3),
(7, 'UnlockUlysses', 'Fast service but a bit pricey.', 4),
(8, 'FeastFred', 'Some dishes were great, but the soup was bland.', 3),
(10, 'NeatNancy', 'Exceptional cleaning, especially in the kitchen area.', 5),
(10, 'TidyTara', 'They missed a spot in the bathroom but overall good.', 4),
(11, 'ListenLinda', 'I found our session helpful, but it was a bit short.', 4),
(13, 'TechyTom', 'Not all functions of my device work post repair.', 2),
(14, 'ParcelPete', 'Delivery was timely, but the box was dented.', 3),
(15, 'AutoAmy', 'They didn’t have the required part. Had to revisit.', 3),
(16, 'BugOffBen', 'They managed the roaches, but ants are still around.', 3),
(19, 'SpotlessSue', 'The team was professional and punctual.', 5),
(20, 'MoveMarty', 'The team was efficient, but a vase was broken in transit.', 3),
(21, 'GourmetGreg', 'Loved the main course, but the dessert lacked flavor.', 3),
(22, 'RevvedUpRaj', 'Decent service, but took longer than promised.', 3),
(24, 'DelishDebbie', 'Amazing taste, but portions were a bit small.', 4),
(26, 'WateryWill', 'The leak is fixed but they left a mess behind.', 3),
(27, 'PackPaul', 'Packing was meticulous, but delivery was delayed.', 3),
(28, 'CrunchyChris', 'Pastries were good but not the best I’ve had.', 3),
(2, 'FacialFay', 'Not as relaxing as I’d hoped. Ambiance was noisy.', 2),
(3, 'VroomVic', 'Charged more than the initial estimate given.', 2),
(6, 'MotorMolly', 'Fixed the engine but the AC stopped working.', 2),
(7, 'KeyKarl', 'Fast but did leave some scratches on the door.', 3),
(9, 'DripDrew', 'Fixed the main issue but now there''s a minor leak.', 3),
(12, 'StitchSam', 'Fit was good but the material feels rough post alteration.', 3),
(23, 'RelaxRoxanne', 'Massage was great but the room was too cold.', 4),
(24, 'TasteTim', 'Good food but not a lot of vegetarian options.', 4),
(25, 'FacialFrida', 'Skin felt a bit irritated post treatment.', 2),
(29, 'BeauteousBella', 'Loved the treatments but the staff was a bit pushy with products.', 3),
(4, 'ShinyShelby', 'Areas were cleaned but they used a very strong-smelling product.', 3),
(5, 'ChicCheryl', 'The stitching is uneven in some places.', 2),
(21, 'HungryHank', 'Flavorful, but a bit too spicy for my liking.', 3),
(14, 'DeliverDave', 'The package was left at the wrong doorstep.', 2),
(18, 'CleanClint', 'Used eco-friendly products, which I appreciate.', 5),
(19, 'DirtDiana', 'Cleaning was alright. Nothing exceptional.', 3),
(11, 'TalkyTara', 'Session felt a bit generic.', 2),
(13, 'TechTina', 'Took longer than other places but the price was fair.', 4);
